/*
 * Auto-generated by CMake.
 * Do not modify or commit to source repository.
 */
 
#ifndef COMPONENT_H
#define COMPONENT_H

#include <orcaice/component.h>

namespace simlocaliser
{

class Component : public orcaice::Component
{
public:

    Component();

    // from orcaice::Component
    virtual void start();
    virtual void stop();

private:
    
    gbxiceutilacfr::ThreadPtr mainThread_;

};

} // namespace

#endif
