/*
 * Auto-generated by CMake.
 * Do not modify or commit to source repository.
 */

#include "component.h"
#include "mainthread.h"
#include <orcaice/proputils.h>

using namespace simlocaliser;

Component::Component()
    : orcaice::Component( "SimLocaliser" )
{
}

void
Component::start()
{
    mainThread_ = new MainThread( context() );
    mainThread_->start();

    // give MainThread a chance to write something to the history
    bool forceHistory = false;
    context().history().autoStart( forceHistory );
    context().history().flush();
}

void
Component::stop()
{
    context().tracer().debug( "stopping main thread", 5 );
    gbxiceutilacfr::stopAndJoin( mainThread_ );
    context().tracer().debug( "stopped main thread", 5 );

    // give MainThread a chance to write something to the history
    bool forceHistory = false;
    context().history().autoFinish( forceHistory );
    context().history().flush();
}
