/*
 * Auto-generated by CMake.
 * Do not modify or commit to source repository.
 */

#include <orcaice/application.h>
#include <component.h>

//
// Build the component into a stand-alone application
//
int main(int argc, char * argv[])
{
    simlocaliser::Component component;
    orcaice::Application app( component, 1 );
    return app.main(argc, argv);
}
