/*
 * Auto-generated by CMake.
 * Do not modify or commit to source repository.
 */

#ifndef SERVICE_H
#define SERVICE_H

#include <orcaice/service.h>

namespace simlocaliser
{

class Service : public orcaice::Service
{
public:

    Service();
};

} // namespace

#endif
