/*
 * Auto-generated by CMake.
 * Do not modify or commit to source repository.
 */

#include "service.h"
#include "component.h"

extern "C"
{
    //
    // Factory function
    //
    IceBox::Service* create( Ice::CommunicatorPtr communicator )
    {
        return new simlocaliser::Service;
    }
}

simlocaliser::Service::Service()
{
    component_ = new simlocaliser::Component();
}
